"""Database schema definitions."""

from .bundles import (
    CONFIDENCE_THRESHOLDS,
    QUERY_FANOUT_SESSIONS_CLUSTERING_FIELDS,
    QUERY_FANOUT_SESSIONS_INDEXES,
    QUERY_FANOUT_SESSIONS_PARTITION_FIELD,
    QUERY_FANOUT_SESSIONS_SCHEMA,
    QUERY_FANOUT_SESSIONS_SQLITE_SCHEMA,
    get_confidence_level,
)
from .clean import (
    CLEAN_SCHEMA,
    CLEAN_TABLE_CLUSTERING_FIELDS,
    CLEAN_TABLE_PARTITION_FIELD,
)
from .raw import RAW_SCHEMA
from .reporting import (
    DAILY_SUMMARY_CLUSTERING_FIELDS,
    DAILY_SUMMARY_PARTITION_FIELD,
    DAILY_SUMMARY_SCHEMA,
    DATA_FRESHNESS_SCHEMA,
    URL_PERFORMANCE_CLUSTERING_FIELDS,
    URL_PERFORMANCE_PARTITION_FIELD,
    URL_PERFORMANCE_SCHEMA,
)

__all__ = [
    # Raw
    "RAW_SCHEMA",
    # Clean
    "CLEAN_SCHEMA",
    "CLEAN_TABLE_PARTITION_FIELD",
    "CLEAN_TABLE_CLUSTERING_FIELDS",
    # Reporting
    "DAILY_SUMMARY_SCHEMA",
    "DAILY_SUMMARY_PARTITION_FIELD",
    "DAILY_SUMMARY_CLUSTERING_FIELDS",
    "URL_PERFORMANCE_SCHEMA",
    "URL_PERFORMANCE_PARTITION_FIELD",
    "URL_PERFORMANCE_CLUSTERING_FIELDS",
    "DATA_FRESHNESS_SCHEMA",
    # Query Fan-Out Sessions
    "QUERY_FANOUT_SESSIONS_SCHEMA",
    "QUERY_FANOUT_SESSIONS_PARTITION_FIELD",
    "QUERY_FANOUT_SESSIONS_CLUSTERING_FIELDS",
    "QUERY_FANOUT_SESSIONS_SQLITE_SCHEMA",
    "QUERY_FANOUT_SESSIONS_INDEXES",
    "CONFIDENCE_THRESHOLDS",
    "get_confidence_level",
]
